// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyD-wtY-bq_XXmKInAS6CR9QitbSd20gjhI',
//     appId: '1:561402072000:web:3f548d128d0840872c1625',
//     messagingSenderId: '561402072000',
//     projectId: 'praywithadam',
//     authDomain: 'praywithadam.firebaseapp.com',
//     storageBucket: 'praywithadam.firebasestorage.app',
//     measurementId: 'G-4801N972XP',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyA41B2hQZ8nFhpsmPXSGpzyWM3pfQ0Jg2c',
//     appId: '1:561402072000:android:58ffd27b9cc8545d2c1625',
//     messagingSenderId: '561402072000',
//     projectId: 'praywithadam',
//     storageBucket: 'praywithadam.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyC0VM3SIwExIHC1fXTE2pf4aj97KGoGNP0',
//     appId: '1:561402072000:ios:85acbb4aab1d19092c1625',
//     messagingSenderId: '561402072000',
//     projectId: 'praywithadam',
//     storageBucket: 'praywithadam.firebasestorage.app',
//     iosBundleId: 'com.example.flutterApplication1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyC0VM3SIwExIHC1fXTE2pf4aj97KGoGNP0',
//     appId: '1:561402072000:ios:85acbb4aab1d19092c1625',
//     messagingSenderId: '561402072000',
//     projectId: 'praywithadam',
//     storageBucket: 'praywithadam.firebasestorage.app',
//     iosBundleId: 'com.example.flutterApplication1',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyD-wtY-bq_XXmKInAS6CR9QitbSd20gjhI',
//     appId: '1:561402072000:web:01b3038ed7611aec2c1625',
//     messagingSenderId: '561402072000',
//     projectId: 'praywithadam',
//     authDomain: 'praywithadam.firebaseapp.com',
//     storageBucket: 'praywithadam.firebasestorage.app',
//     measurementId: 'G-X3NTMJC2QE',
//   );
// }
